/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chess;
import java.awt.event.ActionEvent;
import java.lang.Math;
import java.util.Random;
import javax.swing.Timer;
import java.awt.event.ActionListener;

/**
 *
 * @author Johnszn80
 */
public class Dice extends javax.swing.JFrame {

    /**
     * Creates new form Dice
     */
   static int i = 0;
   Timer t;
    public Dice() {
        initComponents();
        setLocationRelativeTo(this);
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Player2D = new javax.swing.JLabel();
        Player1D = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Button = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 0, 0));

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        Player2D.setForeground(new java.awt.Color(240, 240, 240));
        Player2D.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/leipzig/80/BlackQueen.png"))); // NOI18N

        Player1D.setForeground(new java.awt.Color(240, 240, 240));
        Player1D.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/leipzig/80/BlackBishop.png"))); // NOI18N

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Player 1");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Player2");

        Button.setText("GO!");
        Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonActionPerformed(evt);
            }
        });

        jButton2.setText("Play!");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(Player1D))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Player2D)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2)))
                .addGap(83, 83, 83))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(Button))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Player1D)
                    .addComponent(Player2D))
                .addGap(39, 39, 39)
                .addComponent(Button)
                .addGap(78, 78, 78))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonActionPerformed
           t = new Timer(50, new ActionListener() {
               @Override
               public void actionPerformed(ActionEvent e) {
                 
               Random random = new Random();
               int x = random.nextInt((6 - 1) + 1) + 1;
               int y = random.nextInt((6 - 1) + 1) + 1;
               
               switch(y){
                   case 1:Player1D.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/leipzig/80/BlackBishop.png"))); 
                   break;
                   case 2:Player1D.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/leipzig/80/BlackQueen.png"))); 
                   break;
                   case 3:Player1D.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/leipzig/80/BlackKing.png"))); 
                   break;
                   case 4:Player1D.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/leipzig/80/BlackPawn.png"))); 
                   break;
                   case 5:Player1D.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/leipzig/80/BlackKing.png"))); 
                   break;
                   case 6:Player1D.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/leipzig/80/BlackPawn.png"))); 
                   break;
               }
             
               switch(x){
                   case 1:Player2D.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/leipzig/80/WhiteBishop.png"))); 
                   break;
                   case 2:Player2D.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/leipzig/80/WhiteQueen.png"))); 
                   break;
                   case 3:Player2D.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/leipzig/80/WhiteKing.png"))); 
                   break;
                   case 4:Player2D.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/leipzig/80/WhitePawn.png"))); 
                   break;
                   case 5:Player1D.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/leipzig/80/BlackKing.png"))); 
                   break;
                   case 6:Player1D.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/leipzig/80/BlackPawn.png"))); 
                   break;
                
                 
               }
                  i++;
                   if ( i == 100)
                   {
                       t.stop();
                    
                      
                   }
                 
               }
           });
           t.start();
            
    }//GEN-LAST:event_ButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Dice dice = new Dice();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button;
    private javax.swing.JLabel Player1D;
    private javax.swing.JLabel Player2D;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
